### PR TITLE
new release cloudstack 4.15.1

### PR DESCRIPTION
**Pull request by resmo**
Build is currently failing because of missing dependency:

```
[INFO] Apache CloudStack Plugin - User Authenticator LDAP . FAILURE [  0.188 s]

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:resolve-plugins (resolve-plugins) on 
project cloud-plugin-user-authenticator-ldap: Failure to find com.btmatthews.maven.plugins:ldap-maven-plugin:jar:1.1.3 in
https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update
interval of central has elapsed or updates are forced -> [Help 1]
 ```

### CODE REVIEW

**Comment by rvalle** [comment]
@resmo I think this problem is a configuration management problem with the simulator.

I guess Shapeblue can build it because they have a local copy in their maven repo.

By the look of it I would say the ldap plugin is used during the test to generate data. Most probably a newer version is compatible.

**Comment by rvalle** [comment]
Since updating this plugin in ACS won't happen any time soon, and would require us to create another release, in the mean time:

https://github.com/bmatthews68/ldap-maven-plugin/issues/55

I am contacting the author of this plugin, strangely enough, there are still older versions that 1.1.3, but 1.1.3 is gone.

**Comment by rvalle** [comment]
@resmo we did not get any reply from the ldap-maven, shall  we push an updated dependency to ACS?

**Comment by resmo** [comment]
@rvalle yes, let's do it

**Comment by rvalle** [comment]
I reported the missing artifact.

**Comment by rvalle** [comment]
@resmo , I have now submitted a pull request and the fix is scheduled for 4.15.2

https://github.com/apache/cloudstack/pull/5366

**Comment by resmo** [comment]
closing in favor of #15

**Pull request closed without merging**
