### PR TITLE
new upstream release CloudStack v4.12.0

### PR DESCRIPTION
**Pull request by resmo**
/cc @mattclay

### CODE REVIEW

**Comment by mattclay** [comment]
CI failed: https://app.shippable.com/github/ansible/cloudstack-test-container/runs/9/1/console

```
 ---> Running in 7a3ac79d3994
2019-05-09T21:49:33.988238Z mysqld_safe Logging to syslog.
2019-05-09T21:49:33.991192Z mysqld_safe Logging to '/var/log/mysql/error.log'.
2019-05-09T21:49:34.004186Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Lost connection to MySQL server at 'reading initial communication packet', system error: 104'
The command '/bin/sh -c (/usr/bin/mysqld_safe &); sleep 5; mysqladmin -u root -proot password ''' returned a non-zero code: 1
```

**Comment by mattclay** [comment]
I suspect the newer Docker base image is responsible for the MySQL failure. If that change isn't required, I'd try the PR without that, at least to see if it resolves the issue.

**Comment by resmo** [comment]
weird thing is, that I can not reproduce this locally.

**Comment by mattclay** [comment]
What are you using for your docker host? Some versions of mysql can have problems running in a docker container, depending on the capabilities of the docker host.

**Pull request closed without merging**
