### PR TITLE
fixes issue #17

### LINKED ISSUE #17: Missing admin.json
The admin.json, which is used to configure some tests is missing.

The reason seems to be related to the adoption of the new UI, which seems to have invalidated the default location of nginx making the file no longer accessible.

Possibly was introduced here: 
https://github.com/ansible/cloudstack-test-container/commit/5fdebeef63fd970ecdab1c2fc471cfb31c47d1ab#diff-a271d01fdc5446d154d1923626e45f77e97cce81d6393c145dda6a4c757a32f9R20

### PR DESCRIPTION
**Pull request by rvalle**
closes #17 by adding an explicit location that does not clash with the new ACS UI.

### CODE REVIEW

**Comment by rvalle** [comment]
@resmo if you could merge and generate a new container that would be great!

**Comment by resmo** [comment]
LGTM!

@mattclay this would be ready to merge for a v1.6.1

**Review by mattclay — APPROVED** [review]

**Comment by resmo** [comment]
@mattclay thx!

**Comment by mattclay** [comment]
@resmo Can you test this new container and open a PR to update ansible-test to use it?

**Comment by resmo** [comment]
@mattclay will do.

**Comment by resmo** [comment]
https://github.com/ansible/ansible/pull/81319

**Pull request merged**
